apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: sandbox-app
type: Opaque
stringData:
  POSTGRES_USER: devuser
  POSTGRES_PASSWORD: devpassword
  POSTGRES_DB: locations
  DATABASE_URL: postgresql+psycopg2://devuser:devpassword@postgresql.sandbox-app.svc.cluster.local:5432/locations
  REDIS_PASSWORD: devredis
