apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: sandbox-app
type: Opaque
stringData:
  MAPBOX_ACCESS_TOKEN: "pk.eyJ1IjoidGpwcm9oYW1tZXIiLCJhIjoiY2xwbWExd3FsMDcxZTJ1bzV0NW1zczlwcCJ9.e9r1fI4oHRvY2moe-SZv3w"
  PUBLIC_API_BASE_URL: "http://api.photo.local"
