apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: sandbox-app
type: Opaque
stringData:
  MAPBOX_ACCESS_TOKEN: "REPLACE_WITH_MAPBOX_TOKEN"
  PUBLIC_API_BASE_URL: "http://api.photo.local"
