apiVersion: v1
kind: Service
metadata:
  name: locations
  namespace: sandbox-app
  labels:
    app: locations
spec:
  selector:
    app: locations
  ports:
    - name: http
      port: 80
      targetPort: 9000
