apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-route
  namespace: sandbox-app
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: sandbox-gateway
      namespace: sandbox-app
  hostnames:
    - sandbox.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: api
          port: 8000
