apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sandbox-gateway
  namespace: sandbox-app
spec:
  gatewayClassName: contour-sandbox
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: sandbox.local
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-notify
      port: 80
      protocol: HTTP
      hostname: notify.sandbox.local
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-frontend
      port: 80
      protocol: HTTP
      hostname: ui.sandbox.local
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-photo-api
      port: 80
      protocol: HTTP
      hostname: api.photo.local
      allowedRoutes:
        namespaces:
          from: Same
