apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-service
  namespace: sandbox-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-role
  namespace: sandbox-app
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-binding
  namespace: sandbox-app
subjects:
  - kind: ServiceAccount
    name: sandbox-service
    namespace: sandbox-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sandbox-role
