apiVersion: v1
kind: Secret
metadata:
  name: sandbox-secrets
  namespace: sandbox-app
  labels:
    app.kubernetes.io/name: sandbox-secrets
type: Opaque
data:
  api-key: ZGV2LWFwaS1rZXk=
  notifications-key: ZGV2LW5vdC1rZXk=
